# Header
menu:
  归档: /archives
  RSS: /atom.xml

author: PuchiPuchi
aboutme: Wingardium Leviosa.

# Content
excerpt_link: VIEW MORE
fancybox: true
date_format: 'YYYY年MM月DD日'

socials:
  dribbble: "https://dribbble.com/linxiaopeng"
  github: "https://github.com/linxiaopeng"
  email: "linxiaopeng.my@gmail.com"



# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

#主题方案
highlight_theme: atom light

# widget behavior
archive_type: 'monthly'
show_count: false

disqus_shortname:

# Miscellaneous
google_analytics: UA-123409950-1
gauges_analytics:
favicon: /images/avatar.png
avatar: "/images/avatar.png"
twitter: "https://twitter.com/linxiaopeng_"
dribbble: "https://dribbble.com/linxiaopeng"
fb_admins:
fb_app_id:
